const refs = {
  search: document.querySelector('.search-form'),
  catalog: document.querySelector('.poster-list__item'),
  list: document.querySelector('.poster-list'),
  form: document.querySelector('.header__search-form'),
  warning: document.querySelector('.header-message'),
  toTopBtn: document.querySelector('.btn-to-top'),
  divError: document.querySelector('.to_main__div'),
  modalBackdrop: document.querySelector('.modal-backdrop'),
  btnOnModalTeam: document.querySelector('.team-link'),
  filterForm: document.querySelector('.filter_form'),
  libCatalog: document.querySelector('.poster-lib__item'),
  lib: document.querySelector('.poster-lib'),
	logo: document.querySelector('.header__logo'),
  movieModal: document.querySelector('.modal'),
};

export const {
  search,
  catalog,
  list,
  form,
  warning,
  toTopBtn,
  divError,
  modalBackdrop,
  movieModal,
  btnOnModalTeam,
  filterForm,
  libCatalog,
  lib,
	logo,
} = refs;
